### PR TITLE
Update

### PR DESCRIPTION
**Pull request by Justman100**

### CODE REVIEW

**Comment by xPaw** [comment]
The eslint config doesn't support new major eslint version yet, I'll update the deps later.

**Comment by xPaw** [comment]
The `^` versions don't need bumping as there is no lock file in the repo.

**Comment by Justman100** [comment]
> The `^` versions don't need bumping as there is no lock file in the repo.

And? You could have simply merged with just one or two clicks! Would that really have hurt so much? Instead of destroying the work of others...

**Comment by xPaw** [comment]
You blindly and unnecessary bumped all the versions, eslint-config-standard currently does not support eslint 9.

**Comment by Justman100** [comment]
> You blindly and unnecessary bumped all the versions, eslint-config-standard currently does not support eslint 9.
> 
> https://docs.npmjs.com/about-semantic-versioning#using-semantic-versioning-to-specify-update-types-your-package-can-accept

Then I could just reset the part?

**Pull request closed without merging**
