### PR TITLE
Added SteamDB button to store search

### PR DESCRIPTION
**Pull request by Revadike**
Resolves https://github.com/SteamDatabase/BrowserExtension/issues/20

Todo:
 - [x] Add a button on the store search page
 - [x] Generate the SteamDB equivalent link from the store search query
 - [x] Button styling
 - [x] Adjust button link to changing query
 - [x] Code consistency with the rest of the codebase

### CODE REVIEW

**Comment by xPaw** [comment]
I looked at this again, and if you have multiple checkboxes in the store search, it really doesn't map to steamdb in any meaningful way.

So I'm not entirely sure what usefullness of this is.

**Comment by Revadike** [comment]
It will serve its purpose. For example, searching for a developer in the steam store, then go to steamdb to see the hidden games.

**Comment by xPaw** [comment]
Developers have a separate page now on the store though.

**Comment by xPaw** [comment]
Gonna close this as I have no plans to add this.

**Pull request closed without merging**
